### ISSUE TITLE
Long delay between deploying a bundle to the canvas and it actually appearing.

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1131]
When you "add to canvas" a bundle it takes a considerable amount of time to actually show up on the canvas. This is because we will get a few wss errors about invalid frame headers before it eventually succeeds:

`WebSocket connection to 'wss://demo.jujucharms.com/ws' failed: Invalid frame header`

We should show a notification when this action is performed in the event of a delay but the above issue should be fixed as well.

**Comment by frankban** [comment]
I don't think that error is responsible for the delay you are experiencing. Can it be poor network connection? This is what happens AFAICT when you start deploying a bundle:
1. the GUI connects a WebSocket to "wss://demo.jujucharms.com/ws". That's the demo site, runnign teh GUI server (for now);
2. the GUI correctly tries to send a Client.GetBundleChanges request: that's the new juju-core request to retrieve bundle changes;
3. if the end point is implemented, the changes are displayed and the WebSocket connection is close; otherwise the connection is closed and an error is returned to the environment; the caller (go.js) knows if the error is due to the endpoint not being implemented and can react accordingly. This is the case for the GUI server, and the environment in these cases falls back to trying the legacy ChangeSet.GetChanges call, only implemented by the GUI server;
4. the GUI re-establishes a WebSocket connection to "wss://demo.jujucharms.com/ws";
5. as mentioned the GUI sends a ChangeSet.GetChanges message to retrieve bundle changes;
6. the GUI gets the changes and closes the connection.

Now chrome has a bug that shows an "Invalid frame header" error when the client tries to close a WebSocket connection. It is possible to dupe that just by doing the following:
```javascript
var ws = new WebSocket('wss://demo.jujucharms.com/ws');
// Wait a couple of seconds for the connection to be established.
ws.close();
```
Note that this only happens in chrome and when connecting to the demo site, you should not see errors in the Firefox console.

That's the reason we see two errors while deploying a bundle, because we close the connection at step 3 and 6. I don't think that those errors take so much time to sensibly slow down the changeset process. However, the double roundtrips and the need to establish a WebSocket connection can on very poor networks I guess. To be clear, the errors will never happen when the GUI is connected to a recent (and real) Juju model/controller.

**Comment by hatched** [comment]
Thanks so much for the thorough reply @frankban! The connection here is quite poor so any round trip can take multiple seconds. I guess the error was a red herring. So the actionable item here then is to simply add a notification that we're fetching the bundle data and to wait.
