### ISSUE TITLE
If you add a bundle and then move the services and then deploy the services move back to their original position

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1232]
If you add mediawiki-scalable and then move the services around and then deploy, the services move back to their original x and y position.

**Comment by hatched** [comment]
This is because bundles have x,y annotations set on 'add-to-canvas' whereas individual services do not until after they have been deployed to the Model. After a discussion with @makyo we decided that the best course of action here would be to set the box x, y position using any bundle annotations but not setting the actual annotation until juju responds with a position.
