### ISSUE TITLE
When you click "More" in the environment switcher it opens a white box which is the wrong size and you can't click on the canvas background to close it.

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#1252]

**Comment by hatched** [comment]
Is this supposed to appear to 'hover' like the charmbrowser?

**Comment by Lucapaulina** [comment]
When the user clicks more it should take the user to the profile page which shows everything the user has access to. I imagine the white box was implemented because we don't have the profile page in the GUI just yet so the white box is an interim solution.

I'm not sure what you mean by hover like the charmstore.

**Comment by hatched** [comment]
Yeah this was just an interim implementation. When I mean 'hover' I mean that it doesn't go to the edge of the page and has a dropshadow.

**Comment by Lucapaulina** [comment]
So, I guess we can close this? @hatched

**Comment by hatched** [comment]
@Lucapaulina well we can still update the positioning of the element to have the spacing around the edges with the drop shadow.

**Comment by Lucapaulina** [comment]
When you click more it should take you to this page:

https://github.com/CanonicalLtd/juju-design/tree/master/Profile

**Comment by huwshimi** [comment]
The page that @Lucapaulina mentioned is now implement and will be released with 2.1.0.
