### ISSUE TITLE
Canvas/machine view switcher includes containers in the machine count

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1285]
Add a machine and then add a couple of containers in the machine view. Notice that above the inspector the counts for "0 services | 3 machines" will include the number of containers, not just machines.

**Comment by hatched** [comment]
@Lucapaulina I thought that this was intentional, have any feedback on this?

**Comment by Lucapaulina** [comment]
The goal of the machines count is to show users their resource usage on
their chosen cloud. It should only show the quantity of machines because
thats what they'll be paying for. It also highlights the density of the
model, 3 services on 3 machines or 3 services on 1 machine. If we count
containers too then we can't facilitate both of those use cases.
