### ISSUE TITLE
The root container should be counted in the MV container listing

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#1377]

**Comment by huwshimi** [comment]
I think we've had that in the past and we removed it due to some confusion about the root container not actually being a container. Really the root container is just "on the machine, not inside a container". Happy to change the count, but I wanted to check before we created confusion again.

It might be that we need to figure out how to better represent the units that are on the machine, but not inside a container.

**Comment by Lucapaulina** [comment]
We'll look at this when we work on MV in the next few weeks.

**Comment by hatched** [comment]
Closing this as it's a duplicate
