### ISSUE TITLE
Missing content from charm details

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1516]
- [x] In the design (linked below) we have a section under the description for tags which is missing.
- [x] Embed this charm box next to the readme is missing.

Comparison URLs:
https://jujucharms.com/hadoop/trusty/16
https://demo.jujucharms.com/?store=trusty/hadoop

Charm details design:
![combo-button-01](https://cloud.githubusercontent.com/assets/5873394/14313184/08539e62-fbe8-11e5-94b0-215fcbab89a9.png)

**Comment by hatched** [comment]
IIRC we didn't show the tags because we weren't able to fetch the tags with the charm details request. This may have been fixed now.

As far as adding the juju-cards to the GUI, I'm not sure this has been discussed yet. Do we want to add another dependency that makes separate requests or should we roll our own that uses the data supplied in the charm query?

**Comment by Lucapaulina** [comment]
I don't understand any of those words :) maybe @anthonydillon can help!

**Comment by anthonydillon** [comment]
I would lean towards adding another dependency to keep the cards
consistent. They are changing regularly and keeping them in sync would be a
pain.

**Comment by huwshimi** [comment]
These items have now been done.
