### ISSUE TITLE
Machine view shows UUID on demo.jujucharms.com in the machine column

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1560]
Check out second column.

**Comment by hatched** [comment]
The page <title> also shows the UUID. 

The machine view UUID display is caused by this line: https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/app.js#L2013 We should just be showing Sandbox instead of the UUID. This was put here for a workflow that was modified and never updated.

**Comment by huwshimi** [comment]
I believe this was fixed in #1596. Please reopen this if it can still be reproduced.
