### ISSUE TITLE
Uncommitted changes are lost if you navigate to the profile

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1729]
If you navigate to the profile when you have uncommitted changes you will lose the changes as there is no way to navigate back to your current model.

We can't just disconnect when you navigate back to the model as the controller case needs an active connection to list models etc.

We could potentially show the uncommitted changes popup when the user clicks on the profile (we'd just need to implement that for every profile nav link).

**Comment by anthonydillon** [comment]
I'm not a fan of showing the uncommitted pop-up when the user navigates to
there profile because they are not leaving the GUI so why would they lose
changes, the user will think. This is a good reason to have a close profile
somewhere on the profile page. So the user can just go back to the model
there are connected to without reconnecting.

**Comment by Lucapaulina** [comment]
The way that we designed the profile is so users can't be "in" the profile
or the canvas at the same time, the main issue affecting this concept is
that we don't have persistence of the model change log. Arguably
persistence isn't much help if you're switching between models unless the
delta is stored for each model. Do we have a time frame of when this will
be implemented? If it's soon then we might not need to change anything.

At a minimum we should just force a browser notification explaining that
leaving this page will result in the loss of uncommitted changes, this way
the user is at least given a choice. The uncommitted changes popup could be
nice but we would have to have some kind of message to explain why they
can't leave.

**Comment by hatched** [comment]
I thought that right now we have a warning when going to the profile that the user is going to lose their uncommitted changes? I'm pretty sure I saw that yesterday while qa'ing.

@Lucapaulina It will be a very long time, if ever, until we introduce persistence, it's an incredibly complicated feature to implement. So right now we have to remain connected to the model while in the profile view because that's how we actually get the data for the profile view in certain situations. But we do not allow the user to 'close' the profile view.

**Comment by huwshimi** [comment]
@hatched you must have seen that in my branch that disconnected the model before loading the profile (which is now defunct).
