### ISSUE TITLE
Deploy changes always returns Could not *. Server responsed with: unknown object type "Client".

### ISSUE THREAD

**Issue by vmorris** [juju/juju-gui#1814]
## Versions
$ juju --version
2.0-beta10-xenial-amd64
$ juju upgrade-gui
Juju GUI at version 2.1.2

Trying to do anything inside the GUI is failing with errors as is shown in the attached screenshot.

![selection_104](https://cloud.githubusercontent.com/assets/6424736/16466616/72c5c8a2-3e09-11e6-90a4-23966efd1545.png)

**Comment by hatched** [comment]
Thanks for the bug report! This is a known issue with `2.0-beta10` and is caused by facade changes in juju-core. 

More information can be found here: https://github.com/juju/juju-gui/issues/1780#issuecomment-227226545. 

The next release of the GUI, 2.1.8, will be updated to support these new facades and we expect to have this released later next week.
