### ISSUE TITLE
Newly added applications take a considerable time to switch to pending with 2.1.8

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1820]
Now that we 'addCharm' before deploying the applications on commit the application stays in 'uncommitted' state for a considerable time. This is because we don't get the 'ack' back from Juju until the charm has successfully been added and it has to download it. We then don't switch to pending until the deploy 'ack' which comes after the 'addCharm'. We should instead switch the applications/units to pending immediately after hitting commit.

**Comment by anthonydillon** [comment]
Remember to set a useful workload message too.

**Comment by makyo** [comment]
This is one of those bugs that is larger on the inside than it appears from the outside (does that make it a TARDIS bug?).  The problem boils down to the fact that addCharm is now separate from deploy, so we don't get an ack back on the deploy call until addCharm is done.  Unfortunately, the status of the application isn't based around a single flag, but the aggregate agent_states of the application's units.  @hatched and I discussed a few approaches:

* Rework the logic that decides the class which is applied to the application block.  We rejected this because it's quite fragile as it is, and an inelegant solution is only going to cause us further headaches and could introduce races.
* The lazyAddCharm method of the ECS could update the status of the units of the ghost service (which, at this point, are actually ECS records).  This was rejected for two reasons:
    1. if the addCharm call fails, we then have to roll back these changes, and such a mechanism doesn't currently exist in the ECS.
    2. This would mean modifications to ECS records other than the current modifications of replacing stand-in IDs with real IDs as entities are created, an approach that feels hacky - the ECS ought to be the source of truth with regards to the API calls that will be made and the responses returned.

At this point, the bug will remain for the 2.1.9 release - but will remain on the 2.2.0 milestone - until a better solution can be come up with.  The risk of introducing tech debt for a non-blocking issue in order to cut a release is too high.

**Comment by hatched** [comment]
Thanks for outlining what we discussed here @makyo . I just wanted to also add a potential fix that we discussed might be the best way forward. 

In the topology/service.js `updateServiceNodes` method we give the application icon on the canvas a blue border for 'uncommitted' by setting `pending` to true on the application model. This `pending` needs to be updated to be `uncommitted` and then use the `pending` key as an indicator to turn the status yellow instead of relying on looping through all of the units. There is considerable logic in this method that could/should be simplified. 

It's unknown at this moment what far reaching implications this rename/addition could cause so it's been decided (as mentioned) that this will remain undone for 2.1.9.

**Comment by makyo** [comment]
Thanks, @hatched - I realized I forgot to specify where this would take place.  The first solution I outlined as well as yours would take place primarily in `updateServiceNodes`.  The second solution would involve adding a `prepare` option to the `lazyAddCharm` method in the ECS.

**Comment by Lukewh** [comment]
@hatched @makyo is this remaining undone beyond 2.9.2? Is it still relevant?

**Comment by hatched** [comment]
Yes it's still relevant

**Comment by hatched** [comment]
This has now been fixed with 2.10.0
