### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by wurde** [juju/juju-gui#1858]
Any sort of action performed after logging into the GUI gets some form of "unknown object Client". I'm using juju 2.0-beta11.1 on both a localhost (LXD) and Google cloud with same results. The GUI is not essential to operate juju, but it would be extremely helpful and I did design some cool charm icons.

- None of the existing deployed applications are visible.
- None of the store charms can be deployed.
- No display of current model or select option, just shows "admin@local".

![nothing](https://cloud.githubusercontent.com/assets/5455357/16960999/3e6cbd6a-4db1-11e6-87ee-4d1e7d68dcae.png)

**Comment by hatched** [comment]
Hi @wurde, sorry for the inconvenience.

This is a known issue with the version of the GUI which ships with the beta version of Juju. The facades were changed in Juju core which required a new GUI release. This release however we aren't able to roll out because it will break the default install in Xenial. Unfortunately we are in a little no-mans-land here until the default Xenial version of Juju upgrades to the latest facades and we can update the GUI.

In the mean time please use this release: https://github.com/juju/juju-gui/releases/tag/2.1.8

To upgrade the GUI:
Download the tar.bz2
Run juju upgrade-gui path/to/release

**Comment by wurde** [comment]
I'll try upgrading to 2.1.8. Also I'm glad a solution is pending next release. Thanks.
