### ISSUE TITLE
Importing an exported bundle fails with an error

### ISSUE THREAD

**Issue by rbclark** [juju/juju-gui#1937]
I am currently using the current juju beta: `2.0-beta15-xenial-amd64`. I have a bundle which I have exported using the juju gui and not modified which is can be found here: [default-2016-08-16.txt](https://github.com/juju/juju-gui/files/425430/default-2016-08-16.txt). When I attempt to import this bundle back into the juju gui I get the following error:

    The following errors occurred while retrieving bundle changes: cannot read bundle YAML: 
    cannot unmarshal bundle data: yaml: unmarshal errors: line 1: cannot unmarshal !!str 
    `xenial` into charm.legacyBundleData

I am able to reorder the contents of the yaml file and then get it to import, however attempting to import in the order which it was originally exported fails.

**Comment by hatched** [comment]
Thanks for filing the issue @rbclark we'll take a look into this and get back to you.

**Comment by hatched** [comment]
When importing this bundle into the GUI the RPC call to fetch the changes: 

`{"type":"Client","request":"GetBundleChanges","params":{"yaml":"\"xenial\""},"version":1,"request-id":17}`

It appears that the GUI doesn't like to import bundles where the top level key is `applications` instead of `services`. Making that change allows the data to be correctly sent to fetch the changes. It then complains about invalid constraint values:

`"invalid constraints "arch=amd64 cpu-cores=24 mem=49152 undefined=default" in machine "0": unknown constraint "undefined""`

which are reproduced for every machine:

```yaml
machines:
  "0":
    series: xenial
    constraints: "arch=amd64 cpu-cores=24 mem=49152 undefined=default"
```

**Comment by hatched** [comment]
Sorry for the inconvenience @rbclark I've attached a modified version of the bundle file which ingests correctly. 

[default-2016-08-16-modified.txt](https://github.com/juju/juju-gui/files/425480/default-2016-08-16-modified.txt)

Unfortunately any bundle that's exported from the GUI will exhibit the same issues and need the same modifications made until this issue is resolved.

**Comment by rbclark** [comment]
Thanks, that did fix it! I'm not sure exactly why the undefined=default was added to every one, that may be a separate bug that's happening as I didn't add that manually.

**Comment by hatched** [comment]
@rbclark This issue has now been resolved in the development branch of the GUI and will be in the next release.

The `undefined=default` was another bug which has also been resolved.
