### ISSUE TITLE
Juju2.0 Controller SSO uses pop-ups, can it not?

### ISSUE THREAD

**Issue by BryanQuigley** [juju/juju-gui#1952]
In both Chrome and Firefox.  
1. Go to juju gui in juju 2.0-beta16
2. Click on Login with USSO.
3. In both cases, Pop-ups are blocked and the login never succeeds

Unblocking just one pop-up is the workaround, but it would be nice if the juju-gui didn't depend on pop-ups at all as they are blocked by default.  The pop-ups go to api.jujucharms.com/identity/v1/login....

**Comment by hatched** [comment]
Thanks for bringing this up @BryanQuigley 

Unfortunately the usso auth flow requires this type of login system but right now those windows are opened up by JavaScript and as such are blocked by default. We may be able to modify the button so that it's an anchor tag that will eliminate the window being blocked.

Some investigation for this will be necessary as we also use this type of flow in other places in the GUI.

**Comment by frankban** [comment]
Closing this one in favour of #2438
