### ISSUE TITLE
Juju GUI fails to associate applications with allocated units

### ISSUE THREAD

**Issue by chuckbutler** [juju/juju-gui#2017]
I've run a deployment of observable-kubernetes, which in turn did not yield a successful deployment. This might be a duplicate manifestation of #1614 - however the deployment does work when used via the command line

Steps to reproduce:

1) juju bootstrap a controller
2) juju gui and login
3) search for "observable kubernetes"
4) Click on the banner-link to deploy kubernetes

![](http://i.imgur.com/BlEK27f.png)

5) Observe as all the applications show up in the GUI canvas, and cross reference with juju status.. there are missing applications

A refresh of the GUI illustrates how many of the charms did not make it to their final machine designation.

The Javascript console shows a little output about not finding charms, that are otherwise deployed when executed via:

`juju deploy observable-kubernetes`

![](http://i.imgur.com/4BmuLHh.png)

**Comment by hatched** [comment]
The bundle as uploaded to the store appears to be incorrectly generated and has some incorrect charm IDs. I was not able to reproduce this bundle output using the latest GUI. 

There is however the case where this bundle can still be imported using the CLI and cannot via the GUI. This is because the GUI deployment strategy resolves to the proper ID but the addCharm call does not. This means that the GUI should make a request for the canonical charm ID when importing a bundle as the CLI does to prevent issues like this in the future.

**Comment by chuckbutler** [comment]
@hatched here's the output of a re-import via the CLI and export using the latest Juju GUI

https://gist.github.com/chuckbutler/f7bf9f4a0db1fed93ced8f3a18ccaf9e
