### ISSUE TITLE
Error notification should not appear unless you try to commit a change

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2083]
Example: An error appears when you clear the name field of the model in the first sceen of the deployment flow. This should not happen unless I try to leave that field empty.

![screen shot 2016-10-04 at 10 46 32](https://cloud.githubusercontent.com/assets/12827541/19069884/c27f5b20-8a20-11e6-9a72-57311ea53b02.png)

**Comment by hatched** [comment]
If that's the case we will need some system to show the user that this failed. The deployment page is quite long and simply not committing because there is an error doesn't show the user how to successfully continue.

**Comment by anthonydillon** [comment]
I believe Design/UX do want these messages but they only want the messages
when the user has submitted the form. The Current behaviour is triggered on
input blur which makes this message appear if you focus on a field then
move to the next one without entering anything.

**Comment by hatched** [comment]
Yes, and I'm disagreeing with that :) If we aren't going to show any feedback until it's submitted then we need something at the deploy button telling the user that there are issues above and what those issues are.

**Comment by elvirafigueras** [comment]
So the way this currently works is that I click on the input field and as soon as I clear it a warning message appears.

My intention at this stage is not to leave it blank, it's simply to clear the field so I can populate it with something different, so I should not get an error then because I haven't moved away from it. I should only get an error (at that stage, not when it's submitted) if I then move to the next field one without entering anything.

**Comment by frankban** [comment]
I think the deployment flow now has the behavior Elvira described.
