### ISSUE TITLE
Subordinate unit details show principal unit details

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2309]
**How to reproduce**

1. Deploy a subordinate Charm and connect it to a principle charm (for example spark->zeppelin in the [apache hadoop zeppelin bundle](https://jujucharms.com/apache-hadoop-spark-zeppelin/)).
2. Click on the subordinate charm and choose 'units'

**What I expect:** The GUI shows the units of the subordinate Charm.

**What happens:** The GUI shows the units of the principle Charm.

**Why this is bad:**

1. You cannot see the status message of the subordinate Charms in the GUI.
2. You cannot see the opened ports of the subordinate Charms in the GUI. Subordinates like the `zeppelin` charm in the [apache hadoop zeppelin bundle](https://jujucharms.com/apache-hadoop-spark-zeppelin/) deploy a GUI accessible with the browser. The IP/Port combination of this GUI isn't visible in the GUI. You can only see it in the commandline.

**Comment by hatched** [comment]
Thanks for bringing this up @galgalesh 

It was intentional to show the principle charm because a subordinate could be installed on multiple charms and sometimes you want to see what those units are. This approach clearly has the limitations that you outlined so we will need to come up with something better.
