### ISSUE TITLE
Inspector > Configure - Wrong height of input fields until user starts typing

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2378]
The height of the input fields is smaller by default on empty fields. This is not being fixed until starting typing.

![2017-02-02 13 00 00-1](https://cloud.githubusercontent.com/assets/22299251/22551147/7d3b77e4-e94b-11e6-918c-4aba09e23214.jpg)

**Comment by hatched** [comment]
Thanks for the bug report @ClaraLavina which version of the GUI and which browser?

**Comment by ClaraLavina** [comment]
Firefox 50.1.0 (default install of Ubuntu)
The version of the GUI is the one from Juju 2.0.2-xenial

@hatched I hope this helps you

**Comment by kadams54** [comment]
This seems to be a Firefox-specific bug. I was not able to replicate in Chrome. To replicate:

1. Add the Mediawiki charm to the canvas.
2. Click on "Configure" in the inspector.
3. The admins input field is too small. If you click into it and type something, it grows to the correct size.

Note: In the past Firefox has has problems with input field heights due to an internal CSS bug that ignores line-height. Consequently the only reliable way to set input heights was with padding. I'm not sure if that bug is still around or even applicable in this situation, but it seemed worth mentioning.

**Comment by huwshimi** [comment]
Unassigning from me so that someone else can pick it up if they have a chance to do it before I do.
