### ISSUE TITLE
Search results - invalid series error

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#2401]
- Search for apache2
- Click apache2-20 (latest version trusty)
- App crashes 'invalid series: "apache2-20"
- Change url from '/trusty/apache2-20' to '/apache2'
- Charm is shown

This seems inconsistent. Some charms/ bundles work, others throw this error.

**Comment by hatched** [comment]
This is caused by the hack[0] to support the old urls in the charmstore. We can either fix the hack to better distinguish the paths or properly update the charmstore so that it doesn't link to old urls. I propose the latter.

[0] https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/components/entity-details/entity-details.js#L211
