### ISSUE TITLE
lack of helpful context when you click on "start modeling" 

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2464]
in the beta there's a button at the top of the page to start modeling but the context after that feels like it drops off. I'd suggest we investigate starting with the search open or something to help guide users to that next step. Maybe there's an onboarding note needed here.

This is only in the GISF case and should only be from the start modeling CTAs I think to make sure it's not repetitive/coming up in cases where context is more clear.

**Comment by frankban** [comment]
My understanding is that UX is working on this, postponing to fontaine in the meanwhile.

**Comment by cassiocassio** [comment]
![overview of user flow and promotional cards](https://cloud.githubusercontent.com/assets/4593556/24762232/adbdc1a8-1ae5-11e7-8a47-84756e6a9537.jpg)

## notes on a converstation about "Helpful context"

### Next homepage iteration will feature 2x cards

- 'small solutions cards' - reduced, reworked versions of the "Featured solutions"
- To show side-by-side, above the fold

**1. Kubernates**
**2. Hadoop big data**

Each card will offer 

**"QuickDeploy"** initially to take the user to the canvas with that bundle deployed
- soon, to take the user to an accelerated deployment flow, leading to a working model as rapidly as possible
- alternative name would then be "1-click-deploy"
- or "1-click-deploy-on-azure"

and
**"Learn more"** to take the user to a "feature" page

@clara is working on the k8s feature page
@Elvi as worked on the improved big data

**Cards atttributes**
- will be embedeable, as current store cards are
- are promotional - things we create, rather than charm-authors
- made in small numbers - perhaps 3-5 to start

### Storefront
At the moment features 3x cards

**Kirbana | Containers | OpenStack**
These show up heavily in our analytics. Users dont go far from these promoted choices.

tactics
- replace these three promotions with a small range
- display randomly, rotate daily, or some other mechanisms to ring the changes
- pick our promotions from a mixture of things that perform well in organic search, that are new or notable, or that we are proud of and want to promote
- K8s might -always- feature in the three

**The 2 x cards on the homepage and the 3 x cards on the storefront will draw from the same design/code.

**Possible sequence?**

Dependent on:
K8s page to link to
BigData page to link to

then:
2 x Cards on homepage
3 x (more) cards on storefront

finally:
1-click-deploy mechanism added to some/all cards

### "Try the beta"
- popular link in navigation
- doesn't explain what you're going to try

Less impulsive users should be led by:
**"Build your own model**
(a) Browse our pre-build solutions -> Store
(b) Buid a model yourself ->Empty canvas

objective: only users who really meant to go to the empty canvas get there

but for the impulsive...

### Getting started in the canvas
Hints in the GUI
- Easily dismissible
- Only visible to non-logged in visitors
- "No clippy here"
- Learn the essential geography
- If you're not sure what to deploy, try this...
