### ISSUE TITLE
Can't visit /u/team or /u/user from the GUI with URL

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#2476]
Try visiting a list of charms from another team when signed in to GUI. It redirects you back to your profile page. It should try to connect to the model and if that doesn't exist, try to show the content of store.

**Comment by frankban** [comment]
Clicking on charms/bundles on the profile pages also does not work: it raises errors as it tries to use the old style charm store entity URLs. I'll fix that as part of this same branch.

Also note that I requested a quick UX workaround for the fact that, after visiting someone else's profile, there is no way to go back to my profile: we are missing some navigation capabilities.

**Comment by kasiag** [comment]
@frankban @urosj @anthonydillon  Here's summary of a hangout between me, Elvi, Luke and Francesco as well as actions that came out of it:
since this bug is a release blocker we went with a solution of linking the juju logo with user's profile. Therefore regardless of where the user is, in their canvas or looking at someone else's models/ profile if they click on the juju logo, they will be taken back to their original profile. 

We've also proposed to re-visit this implementation at the JAAS sprint w/c 6th March for any changes.
