### ISSUE TITLE
Can't create a new model from the profile

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#2535]
If I load the gui, which redirects me to my profile and then I click on the button to create a new model I get the "Connecting to the Juju model" spinner and it never goes away.

I visit /new it works and if I connect to a real model and then click the new model button it works.

This was tested using Ubuntu and Chrome/Firefox and the latest develop.

**Comment by hatched** [comment]
It appears that this might be a regression caused by this PR https://github.com/juju/juju-gui/pull/2529 

Repro steps: 

- Load the GUI using proxy to prod and log in.
- Visit the GUI at the root path and it'll redirect to your profile.
- Now clicking the Create New will exhibit the noted issue.
- running `app.maskVisibility(false)` however will hide the mask and it will work as expected.

**Comment by hatched** [comment]
@jaycee can you take a look into this plz.

**Comment by jaycee** [comment]
The issue was that /new was only dropping the mask for anonymous mode. Updating the condition to be anonymous mode or credentials being available seems to have fixed it. A PR for this is up.
