### ISSUE TITLE
Opening the store closes your profile

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#2537]
If you're viewing your profile and then click the search box to open the store, then when you close the store your profile also closes so you end up at a model instead of back on your profile.

**Comment by kadams54** [comment]
I wonder if it even makes sense to show the search box on the user profile. Here's why: now, when you go into the store, you see "Add to my-model" buttons on the charm and bundle detail pages. Those buttons only make sense when you're connected to a model, and being in the profile is supposed to be a sort of nebulous in-between state (where you may or may not be connected).

The biggest question mark, to me, is what we do when someone navigates into the store from a direct link. In that case, I think we have to go with their default model for the buttons. The more interesting question: what state should they go to when they close the store? My initial feeling was that it should be the profile, since that's what you get when you nav to the root ('/'); however, as I think more about it I'm leaning more and more towards "default model". The store is pretty closely tied to a model; it doesn't make sense to have it available when you're not in a model.

**Comment by hatched** [comment]
Clicking the add to model button in this case will add it to a new unconnected model just FYI.

**Comment by huwshimi** [comment]
This was fixed by #2879.

**Comment by huwshimi** [comment]
The previously attempted fix introduced #2917.

**Comment by frankban** [comment]
The fix for this is not as straightforward as it initially seemed. I wonder what's the real meaning of going to search the store from the profile page. Anyway, I'd suggest this is a low priority issue for now.

**Comment by hatched** [comment]
We no longer disconnect from a model when switching to the profile so this is no longer a problem.
