### ISSUE TITLE
Deleting a model in the cli leaves the gui in a bad state

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#2567]
From https://github.com/CanonicalLtd/blues_browser/issues/1450.

When you remove a model via the CLI, gui then reflects the removal of all applications, but not the destruction of the model.

![](https://cloud.githubusercontent.com/assets/4275819/20540160/0d92786a-b0c6-11e6-8f9a-4b77027f6080.png)

**Comment by kasiag** [comment]
@spencerbygraves could you take a look at this?

**Comment by huwshimi** [comment]
Related (or duplicate): #1718.

**Comment by huwshimi** [comment]
How can we know when a model has been destroyed? I couldn't see anything being fired in the GUI when it gets destroyed. Do we have to add a watcher somewhere?

**Comment by frankban** [comment]
Yes, we'd need to subscribe to the all-model watcher (which is like the mega-watcher but for all models. That the Controller.WatchAllModels call, that in theory we could use eventually to replace both the mega-watcher and the various ListModels/ModelInfo calls. But this is a work that would involve several steps, like implementing the calls (WatchAllModels and next), the watcher handlers, then replacing the mega-watcher, then implementing the "model" model in out database, that we can use to track changes, then replacing the List/Info calls.

**Comment by frankban** [comment]
Note that my previous comment about the AllModelWatcher is not really actionable as JAAS by design does not implement that API, and even in the simple Juju controller implementation that's only available for the admin. We should realy detect disconnections and react accordingly. So it seems to me that this bug is a special case of https://github.com/juju/juju-gui/issues/2950
