### ISSUE TITLE
"choose a cloud to deploy to" should turn to a green checkmark during DF

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2590]
![selection_004](https://cloud.githubusercontent.com/assets/75915/23680352/e9f3dfa8-0358-11e7-86e7-b34d940b21f9.png)

When I go through and have a "greyed out checkmark" to pick a cloud, once I pick one it should turn green perhaps?

**Comment by huwshimi** [comment]
The cloud and credentials are lumped together so that the checkmark only goes green once you've selected both. Perhaps changing the title to something like "Choose cloud and credential to deploy with" might help, but might make it a little confusing when you're initially only shown a cloud to select.

**Comment by frankban** [comment]
It does now, closing the bug.
