### ISSUE TITLE
Cannot access team namespace charms

### ISSUE THREAD

**Issue by jamesbeedy** [juju/juju-gui#2623]
I can only see charms in my team namespace which have acl of 'everyone'.

![screen shot 2017-03-09 at 10 09 15 am](https://cloud.githubusercontent.com/assets/5590546/23763904/64d00f8c-04b0-11e7-8428-12a4b40a254b.png)

**Comment by frankban** [comment]
I believe this is an effect of the authentication issues we are currently fixing. I presume that you are not really logged into the charm store, due to a bug in the GUI, and that if you retry from scratch (for example by logging in again from incognito) then you would see your private team charms.
Closing this as we are currently tracking (and working on) auth issues as part of other bugs.
Thanks for reporting!
