### ISSUE TITLE
Show charm's release date and by who

### ISSUE THREAD

**Issue by hloeung** [juju/juju-gui#2733]
Hi,

This is mostly out of https://bugs.launchpad.net/nrpe-charm/+bug/1679963 where -14 was released without charmhelpers.core even though it was there in the code repo. Unfortunately, it's hard to figure out who it was released by and when as that information isn't available so the only way to report an issue was to reach out to those who had recently made commits to the charm.

Any chance the Juju GUI / jujucharms.com could show something like "Released: 2017-04-03 by <person>" or something similar?

**Comment by hatched** [comment]
Hi @hloeung, thanks for bringing this up.

The charm details pages have a "submit a bug" and "project homepage" links which can direct you to the appropriate places to file issues for a specific charm if the author has defined those values. We do not have any visibility into what repository, if any, the charm is hosted at beyond those values. When a charm archive is pushed to the store it is pushed as the user shown at the top of the details page, in this case that's `nrpe-charmers`. 

In order to keep track of what code generated a release, charm authors should typically tag a commit to which a release was cut from to mark that as such.

We can certainly look at adding the released date into the entity detail pages. In the short term, if you're looking for the time a charm archive was pushed you can run the following: 
```HTTP
https://api.jujucharms.com/charmstore/v5/nrpe-15/meta/any?include=archive-upload-time


{"Id":"cs:nrpe-15","Meta":{"archive-upload-time":{"UploadTime":"2017-04-05T23:26:07.069Z"}}}
```

**Comment by cassiocassio** [comment]
I feel that the degree of 'freshness / staleness' of a charm is _one_ guide to it's trustworthyness, and  the store will make this info findable - without all the nitty gritty details of the whole release history.

We could show:

Last revision 23 days ago

or if (not the current month)

Last revision 7 months ago

or (not the current year)

Last revision 2016-03-12.


<img width="1256" alt="add the date" src="https://cloud.githubusercontent.com/assets/4593556/25859699/46757494-34d7-11e7-892d-d792cf377572.png">


(The contact should remain via the project homepage - we don't want to be guessing if there is a team, corporate or individual contact details for a project. It's surely up to a project/org to provide the appropriate contact details)
