### ISSUE TITLE
GUI doesn't work with bootstrapped controller

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#2901]
If I bootstrap using Juju 2.2-beta1-zesty-amd64 on AWS and upgrade the GUI to 2.6.0 (develop) and try and load the GUI I get `Uncaught ReferenceError: zip is not defined` and the GUI does not load.

**Comment by frankban** [comment]
We encountered this and this was fixed. The problem was that the minified zip library was not included in the build due to a typo in the Makefile. Could you please confirm that you are seeing this using latest develop tip? Can you also try with the builtin default 2.6.0 release (just bootstrapping without running ugrade-gui)?

**Comment by frankban** [comment]
I tried to dupe this with today's juju develop tip and both GUI 2.6.0 release and GUI develop, without success. So, I am closing this, but of course feel free to reopen the issue if I missed the problem.

**Comment by huwshimi** [comment]
Thanks @frankban, I did a clean-all and it's now working.
