### ISSUE TITLE
h3 and h4 are confusing/backwards in appearance

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2977]
In looking at the Canonical Kubernetes readme I had a hard time understanding this section and I realized it was because I had confused a lower heading (h4) with the main section vs the h3 above it. 

The styles should be adjusted so that h3 and h4 are able to be told as a higher/lower heading style. 
![h3-h4-confusion](https://cloud.githubusercontent.com/assets/75915/26784877/d3d82c72-49cd-11e7-8de2-95c85d453823.jpg)

**Comment by spencerbygraves** [comment]
@Lukewh and I are doing improvements to the details pages, we'll look at the type as part of [this issue](https://github.com/CanonicalLtd/juju-design/issues/200).

Cheers

**Comment by cassiocassio** [comment]
I had glued a bunch of README's together and sorted  the lines, to see how authors are using h1-6 in the real world:

Findings:

- some authors are staying very simple and just using h1 e.g. https://jujucharms.com/landscape-client/28

- some authors are more complex and use the hierarhcy:
https://jujucharms.com/canonical-kubernetes/bundle/132 

- even those who do this, tend to stick to h1-h3

- h4 is used pretty sparingly

- nevertheless, the font-weight in the screenshot above is heavier than the 300 at present: 

![Screen Shot 2017-12-11 at 11.50.39.png](https://images.zenhubusercontent.com/59391bc151aa2c305780dbd6/12c899b9-b0aa-47e9-ac25-af7beb527ea1)

That weight seems to be the main source of confusion. I suspect that got fixed in in the design sprint we had in the summer.


----
Example heading use from a bunch of README's:

# Adding optional storage
# Basic OpenStack Cloud
# Benchmarking
# Configuration
# Contact Information
# Contact Information
# Deploying
# Flannel
# Issues
# Logging
# Monitoring
# Overview
# Overview
# Resources
# Scale out Usage
# Scaling
# The Canonical Distribution of Kubernetes
# Usage
# Usage
# Verifying
## Alternate deployment methods
## Bundle Composition
## Components
## Configuration
## Downloading ElasticSearch
## Elasticsearch
## Ensuring it's working
## Further information
## Interacting with the Kubernetes cluster
## Known Limitations
## Known Limitations and Issues
## Kubernetes details
## Network-Restricted Environments
## Overview
## Proxy configuration
## Requirements
## Scale Out Usage
## Smoke Test
## Status
## Useful Cloud URLs
## Utilities
## What next?
### Accessing the cloud
### Accessing the Kubernetes dashboard
### Accessing your instance
### Attaching a volume
### Booting an instance
### Configure networking
### Configuring a flavor
### Configuring an image
### Control the cluster
### Deploying with Juju directly
### Discovery
### Install OpenStack client tools
### Relating to the Elasticsearch cluster
### Scaling Etcd
### Scaling kubernetes-worker
### Using a specific Kubernetes version
### Using Ingress
### Using with your own resources
#### Clean up example
#### List the ingress resources
#### List the pods
#### List the services and endpoints
#### Minimal getting started
#### Running the packaged example

**Comment by spencerbygraves** [comment]
With the help of @barrymcgee we found a set of README type styles added some time ago. The sizes in that file were not set by the design team as far as I'm aware.

That has led to the h3/h4 problem above, as you can see from the sizes below.

- h1: 23px
- h2: 23px
- h3: 19.2px
- h4: 17.6px
- h5: 16px
- h6: 16px

I've added an item to our backlog to update these README styles for better clarity, without breaking anything that already exists.
