### ISSUE TITLE
Back to canvas from bundle in dd navigates to /login

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2996]
Visit /new?dd=bundle/realtime-syslog-analytics

After a few moments, before it's finished loading, click the "Back to canvas" button. The url will be /login instead of /new. This probably has something to do with https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/components/deployment-flow/panel/panel.js#L46 and because root isn't being set, the url reverts to its old state.

**Comment by huwshimi** [comment]
I think updating the close state would work in this case, but the real problem is that /login hangs around in the URL at all. It should get removed once logged in.

Strangely when logged out you get slightly different symptoms. You don't have /login in the URL and when you click the back to canvas button the DD reloads and starts adding the bundle again.
