### ISSUE TITLE
Check model name conflicts

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3133]
In the deployment flow when naming a model we could check the model name against the user's existing models and validate for conflicts or even append a suffix to make it unique or maybe even give some suggestions to the user.

**Comment by huwshimi** [comment]
The suggested names cold be something like "kubernetes**-test**" "kubernetes**-prod**" "kubernetes**-qa**" etc.

**Comment by cassiocassio** [comment]
1.

We already check in the flow if the name is duplicate, but we do so at the point of clicking "Deploy"

<img width="1680" alt="screen shot 2017-08-31 at 14 28 53" src="https://user-images.githubusercontent.com/4593556/29925625-d18641e6-8e58-11e7-9b14-425b22b8009b.png">

We check validity, capitals and spaces etc when you tab out/onward from the field.

<img width="817" alt="screen shot 2017-08-31 at 14 30 35" src="https://user-images.githubusercontent.com/4593556/29925719-25619ebe-8e59-11e7-85d8-675630d7d196.png">

Could/should we also check for namespace-unique at that moment?

2. 

I think it's going to be very hard to usefully guess what users want to name their models. 

It's more important to teach them that models are not rename-able.

3.

The right solution would be be to make models rename-able.

**Comment by anthonydillon** [comment]
Also I spoke to John about the limits on the model names. They say there is
no requirement to block capitals letters. They only did it because they
thought people might get confused with closely named models. Such as,
`mymodel` and `Mymodel`.

I think we should allow the user to name there models what they like. I
came across this issue when creating models on my phone. A phone keyboard
auto sets the first letter to a capital which is not valid.

It would be nice to reduce the limits and validation.

**Comment by frankban** [comment]
+1 on reducing the limits and on validating the field onChange.
