### ISSUE TITLE
the Title of the getstarted block should just be charm/bundle name

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3294]
See the title.

**Comment by mitechie** [comment]
And the guidelines should not suggest it. 

https://github.com/Lukewh/charmers-tools/blob/master/docs/getstarted/getstarted.md

**Comment by cassiocassio** [comment]
Agree: the author shouldn't be writing this for themselves.

The words "Get started:" should **also** be present. (possibly quite small, at the very top)

Otherwise a user cannot possibly know what clicking on the "Get started" link the inspector will do. We know because we build the feature and we know what the file is called in the archive.

(The easily imagine it might start a service, for example).

We should probably think about how to handle switching between multiple getstarted.mds in a single model too..

![img_0173](https://user-images.githubusercontent.com/4593556/33434501-6573c02a-d5d7-11e7-9f0d-08eddf47ece4.jpg)
