### ISSUE TITLE
launching the juju shell hides and breaks the styling of the save changes button in application config

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3416]
You can no longer find/use the save changes button even if you close the shell and have to reload the page to be able to change config.

**Comment by hatched** [comment]
It turns out that the buttons are still functional but hidden by the terminal UI. Because the terminal height is dynamic there ends up being a time when the expanding UI of the config inspector and the terminal could clash. To attempt to fix this I'll add a drop shadow to the terminal to indicate better that it is on top of the rest of the UI.
