### ISSUE TITLE
Shell pane should close automatically when the connection is closed by the server

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#3461]
There is a notification saying "Terminal connection unexpectedly closed", but the pane is left open and unuseful. If users want to re-establish a jujushell connection they have to close the pane and open it again, which is not a great user experience.

We could also consider to changing the message with something like "Shell connection closed by the server".

**Comment by hatched** [comment]
After discussion this, we won't automatically close the terminal when the connection is closed because there may be information available that the user may want to keep even through a disconnection. Also closing the terminal without a warning would be jarring. Instead we'll expand the notification and provide a way to reconnect.
