### ISSUE TITLE
Closing entity details by the search box X does not return to the canvas

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3481]
To reproduce:
- Add a charm to the canvas
- In the inspector, click the 'charm details' link
- Click the 'X' in the search box, the charm details will still be rendered.
- Click the search box again,
- Click the 'X', it will now return to the canvas.

**Comment by huwshimi** [comment]
This issue comes from `_clearUserEntity` (https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/init.js#L675) being called before `_clearCharmbrowser` (https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/init/component-renderers-mixin.js#L672).

If you comment out the `unmountComponentAtNode` in `_clearUserEntity` then there is no error. I don't know what the correct fix for this is.

**Comment by hatched** [comment]
I've traced the root of this issue to a bug in the state system. When calling `changeState` with a null value'd key to trigger the cleanup method, even if the state doesn't currently contain that key being nulled, it will still run the cleanup method. This is causing the elements to be incorrectly cleaned up.
