### ISSUE TITLE
controller model shows in my profile model list but not the drop down for model picker

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3572]
![dropdown](https://user-images.githubusercontent.com/75915/37087755-81dbd408-21fb-11e8-8603-18ece9e5c9a1.jpg)
![profile-list](https://user-images.githubusercontent.com/75915/37087765-856973fa-21fb-11e8-90cc-c2e8cd4c290c.jpg)

**Comment by hatched** [comment]
This was an intentional decision made some time ago. The idea behind it was that we didn't want people switching, and deploying, to the controller model unless they understood how it's different from the other models. 

I feel that with the new profile changes this surfaces the controller model at a level consistent with the rest of the models so this should no longer be an issue.

We should however remove the trashcan icon from the profile as you can't actually delete the controller model this way.
