### ISSUE TITLE
Missing UI in model/status tab

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#3832]
Moved from https://bugs.launchpad.net/juju-gui/+bug/1796691
```
url /mymodel/i/status

Open a model, existing or new one, and click on 'Status' on the panel. The UI disappears, and you can only see the canvas with the model on it.
After about 30 minutes (at least with the models I tested) the content and the UI appears.
```

**Comment by frankban** [comment]
Hey Claudio, I am not able to dupe the issue in my existing model, could you please provide the bundle or charms you deployed to expose the regression? And is it on JAAS or your own controller? Thanks!

**Comment by clagom** [comment]
Hi @frankban 
This happens when I'm logged-in with any bundle I tried, for example: Canonical Kubernetes, Hadoop Spark. With models are connected to my Google Cloud. On JAAS, but I'll test it on my controller, too.

When logged-out the UI is present with a message "Cannot show the status: the GUI is not connected to a model."

**Comment by frankban** [comment]
Thanks @clagom

**Comment by huwshimi** [comment]
@clagom this should be resolved with the next release of the GUI. Please re-open this if you still have the same issue.
